create table if not exists customer
(
    id      integer generated by default as identity,
    name    varchar(100) not null,
    surname varchar(100) not null,
    email   varchar(100) not null,
    image   bytea
);

alter table customer
    owner to postgres;

alter table customer
    add constraint customer_pk
        primary key (id);

create table if not exists item
(
    id            integer generated by default as identity,
    name          varchar(100) not null,
    image         varchar(100),
    serial_number varchar(50)  not null,
    brand_id      integer      not null
);

alter table item
    owner to postgres;

alter table item
    add constraint item_pk
        primary key (id);

create table if not exists stock
(
    itemid       integer not null,
    stock_amount integer not null
);

comment on column stock.itemid is 'should be same Id as item.';

alter table stock
    owner to postgres;

alter table stock
    add constraint stock_pk
        primary key (itemid);

create table if not exists purchase_log
(
    id          integer generated by default as identity,
    item_id     integer           not null,
    customer_id integer           not null,
    amount      integer default 1 not null
);

alter table purchase_log
    owner to postgres;

alter table purchase_log
    add constraint purchase_log_pk
        primary key (id);

alter table purchase_log
    add constraint purchase_log_item_id_fk
        foreign key (item_id) references item;

alter table purchase_log
    add constraint purchase_log_customer_id_fk
        foreign key (customer_id) references customer;

create table if not exists refund_log
(
    id                  integer generated by default as identity,
    purchase_log_id     integer not null,
    date_time_of_refund date    not null,
    refund_status_id    integer not null
);

alter table refund_log
    owner to postgres;

alter table refund_log
    add constraint refundlog_pk
        primary key (id);

alter table refund_log
    add constraint refundlog_purchaselog_id_fk
        foreign key (purchase_log_id) references purchase_log;

create table if not exists refund_status
(
    id   integer generated by default as identity (start with 1 minvalue -2147483648),
    name varchar(50) not null
);

alter table refund_status
    owner to postgres;

alter table refund_status
    add constraint refund_status_pk
        primary key (id);

alter table refund_log
    add constraint refundlog_refundstatus_id_fk
        foreign key (refund_status_id) references refund_status;

create table if not exists brand
(
    id   integer generated by default as identity,
    name varchar(100) not null
);

alter table brand
    owner to postgres;

alter table brand
    add constraint brand_pk
        primary key (id);

alter table item
    add constraint item_brands_id_fk
        foreign key (brand_id) references brand;

create table if not exists user_account
(
    id          integer generated by default as identity,
    user_name   varchar(50) not null,
    customer_id integer     not null
);

alter table user_account
    owner to postgres;

alter table user_account
    add constraint user_account_pk
        primary key (id);

alter table user_account
    add constraint user_account_customer_id_fk
        foreign key (customer_id) references customer;

create table if not exists permission
(
    id            integer generated by default as identity,
    name          varchar not null,
    allowed_items integer[]
);

alter table permission
    owner to postgres;

alter table permission
    add constraint permission_pk
        primary key (id);

create table if not exists pages
(
    id   integer generated by default as identity,
    name varchar(50) not null
);

comment on table pages is 'reffers to a page of the website, for permission reasons.';

alter table pages
    owner to postgres;

alter table pages
    add constraint pages_pk
        primary key (id);

